### PR TITLE
Renamed lark.py to lark.

### PR DESCRIPTION
**Pull request by zippynk**
It looks more professional.

### CODE REVIEW

**Comment by JacobEdelman** [comment]
According to the commits it looks like you just deleted Lark.py and never made Lark, although the Github app in using might just be confusing me.

**Comment by zippynk** [comment]
Oh.
Did I forget to add lark to the git version control? Just a second.

**Comment by zippynk** [comment]
Done.

**Comment by JacobEdelman** [comment]
I fixed this in one of my pull requests recently, thanks for pointing it out. I think your fix would have deleted the lark.py and created lark instead of renaming lark.py to lark. I also changed the file a bunch.

**Pull request closed without merging**
